---
- name: Download teleport enterprise archive to localhost
  when: teleport_enterprise_mode
  get_url:
    url: "https://get.gravitational.com/teleport-ent-{{ teleport_version }}-{{ teleport_node_arch }}-bin.tar.gz"
    dest: "/tmp/"
  register: _download_teleport
  until: _download_teleport is success
  retries: 10
  delay: 2
  delegate_to: localhost

- name: Download teleport OSS archive to localhost
  when: not teleport_enterprise_mode
  get_url:
    url: "https://get.gravitational.com/teleport-{{ teleport_version }}-{{ teleport_node_arch }}-bin.tar.gz"
    dest: "/tmp/"
  register: _download_teleport
  until: _download_teleport is success
  become: false
  retries: 10
  delay: 2
  delegate_to: localhost
